import "./globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-league-spartan",
});

export const metadata: Metadata = {
  title: "Mr Faraz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={leagueSpartan.variable}>
      <body className="bg-gray-50 antialiased font-spartan">
        <Navbar />
        <main className="relative">
          {children}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar
          />
        </main>
        <Footer />
      </body>
    </html>
  );
}
